
version: 2

models:
    - name: demand_module_sales
      description: '{{doc("demand_module_sales")}}'
    - name: demand_module_stock_value
      description: 'historical inventory levels for all products on all days'
    - name: demand_module_active_products
      description: 'Using a Weighted Range of 30 days after inventory goes to 0 to mark unactive orders'      

